### ISSUE TITLE
Декодировщик нот для мелодии

### ISSUE THREAD

**Issue by Alex-Kuz** [drewxa/pet-project#1]
### Общая задача
Существует много красивых мелодий, которые хотелось бы повторить (быть может на инструменте, отличном от исходного), однако на слух подбирать ноты (табы, аккорды) бывает сложно.

Необходимо реализовать алгоритм **DeBach**  (а лучше его еще и переназвать):
- фортепиано
- гитара
- скрипка
- виолончель
- флейта
- и т.д. 
Алгоритм принимает на вход аудиозапись мелодии выбранного инструмента и возвращает ноты, табы или то, что требуется (например, для фортепиано - ноты, для гитары - табы, аккорды).

### Возможные подзадачи:
1. Очевидно, что для одних и тех же последовательностей нот существуют разные записи (связанные с тональностями). Быстрое решение - игнорировать факт существования тональностей, все ноты в "базовой" до-мажор.
2. Очевидно, что запись длительности нот зависит от такта. Не хотелось бы увидеть запись 1/256 от длительности всей композиции. Быстрое решение - "ничего страшного, и так сойдет".

### Возможные фичи:
1. Прикрутить существующий инструмент, который бы по нотам (табам и тд) воспроизводил бы музыку, на основе которого можно было бы сделать проверку правильности декодирования и использовать либо как тест алгоритма, либо как его составную часть (задача на подумать - как?)

2. Трансляция музыки с одного инструмента на другой: бывает так, что мелодию, сыгранную красиво на одном инструменте, можно сыграть и на другом, не менее красиво. Иногда это сводится к сдвигу на целое число октав (переход от скрипки к виолончели), иногда требуется добавить что-то в звучание (посмотрите, как для рояля адаптируют партии для виолончелей).

### Предлагаемый уровень сложностей:
- Исследование: 4/10
- Реализация: 5/10

### Предлагаемые способы решения:
1. Машинное обучение (лучше и адаптивнее).
2. Анализ частотных характеристик, обертонов, в общем, чистая математика.

**Comment by drewxa** [comment]
тут же все равно будет анализ частотных характеристик даже если ML. фичи-то откуда еще генерить

**Comment by Alex-Kuz** [comment]
Не палите.
